# Generated by Django 3.2.15 on 2022-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
