# Generated by Django 3.1 on 2022-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0005_auto_20201023_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
